[dependencies]
ring = "0.16.20"
pbkdf2 = "0.7.5"
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["server", "tls", "client", "http2"] }
openssl = "0.10.41"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
